services:
  gateway:
    build:
      context: /root/www/edu_rag_platform_be
      dockerfile: gateway/Dockerfile
    container_name: edu-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - edu-net    
    environment:
      - PYTHONPATH=/app
      - DB_HOST=106.12.58.7
      - DB_PORT=5432
      - DB_USER=evan
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=accurate_edu

  service_rag:
    build:
      context: /root/www/edu_rag_platform_be
      dockerfile: service_rag/Dockerfile
    container_name: edu-rag
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - edu-net
    environment:
      - PYTHONPATH=/app
      - DB_HOST=106.12.58.7
      - DB_PORT=5432
      - DB_USER=evan
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=accurate_edu

networks:
  edu-net: