services:
  gateway:
    build:
      context: /root/www/edu_rag_platform_be
      dockerfile: gateway/Dockerfile
    container_name: edu-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - /root/www/edu_rag_platform_be/.env.production
    networks:
      - edu-net    
    environment:
      - PYTHONPATH=/app

  service_rag:
    build:
      context: /root/www/edu_rag_platform_be
      dockerfile: service_rag/Dockerfile
    container_name: edu-rag
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - /root/www/edu_rag_platform_be/.env.production
    networks:
      - edu-net
    environment:
      - PYTHONPATH=/app

networks:
  edu-net: