services:
  gateway:
    build: /root/www/edu_rag_platform_be/gateway
    container_name: edu-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - /root/www/edu_rag_platform_be/.env.product
    networks:
      - edu-net

  service_rag:
    build: /root/www/edu_rag_platform_be/service_rag
    container_name: edu-rag
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - /root/www/edu_rag_platform_be/.env.product
    networks:
      - edu-net

  service_shell:
    build: /root/www/edu_rag_platform_be/service_shell
    container_name: edu-shell
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - /root/www/edu_rag_platform_be/.env.product
    networks:
      - edu-net

networks:
  edu-net: