version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: assurate-nginx-solo
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - edu-net   
    restart: unless-stopped