services:
  nginx:
    image: nginx:1.27-alpine
    container_name: assurate-nginx-solo
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    # networks:
    #   - edu-net
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    restart: unless-stopped